# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Proyecto' do
	
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
	pod 'Firebase/Core'
	pod 'Firebase/Storage'

end
